package http

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"reflect"
	"testing"
	"time"
)

// TestConstructorURL verifies that the URL is properly copied.
func TestConstructorURL(t *testing.T) {
	s := NewStream("the-url.com")
	if s.url != "the-url.com" {
		t.Fatalf("Unexpected url found. Expected: `%s` - Found: `%s`.", "the-url.com", s.url)
	}
}

// TestSetMethod verifies that the SetMethod function
// works as expected.
func TestSetMethod(t *testing.T) {
	s := NewStream("")

	if s.method != http.MethodPost {
		t.Fatalf("Unexpected default method found: `%s`.", s.method)
	}

	s.SetMethod(http.MethodPut)
	if s.method != http.MethodPut {
		t.Fatalf("Unexpected request method found. Expected: `%s` - Found: `%s`.", http.MethodPut, s.method)
	}
}

// TestSetCustomBodyPrepareFunction verifies that the
// SetCustomBodyPrepareFunction function works as expected.
func TestSetCustomBodyPrepareFunction(t *testing.T) {
	s := NewStream("")
	if s.prepareBody != nil {
		t.Fatalf("Unexpected body prepare function found: %+v", reflect.ValueOf(s.prepareBody))
	}

	prepare := func(in []byte) ([]byte, error) {
		return in, nil
	}

	s.SetCustomBodyPrepareFunction(prepare)
	if reflect.ValueOf(s.prepareBody) != reflect.ValueOf(prepare) {
		t.Fatalf("Unexpected request method found. Expected: `%s` - Found: `%s`.", http.MethodPut, s.method)
	}
}

// TestEnableAndDisableHTTPS will verify default value for
// HTTPS usage, then verifies that the EnableHTTPS and
// DisableHTTPS functions properly work.
func TestEnableAndDisableHTTPS(t *testing.T) {
	s := NewStream("")
	if s.useHTTPS == true {
		t.Fatalf("HTTPS should be disabled by default!")
	}

	s.EnableHTTPS()
	if s.useHTTPS != true {
		t.Fatalf("HTTPS should have been enabled!")
	}

	s.DisableHTTPS()
	if s.useHTTPS != false {
		t.Fatalf("HTTPS should have been disabled!")
	}
}

// TestFireRequest successfully fires an HTTP PUT request.
func TestFireRequest(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		if r.Method != http.MethodPut {
			t.Fatalf("Unexpected request method. Expected: %s - Found: %s.", http.MethodPut, r.Method)
		}

		// Read body.
		payload, err := ioutil.ReadAll(r.Body)
		if err != nil {
			t.Fatalf("Error reading body: %v", err)
			return
		}
		defer r.Body.Close()

		if len(payload) != 3 {
			t.Fatalf("Unexpected number of bytes read. Expected: %d - Found: %d.", 3, len(payload))
		}
		if bytes.Compare(payload, []byte("hey")) != 0 {
			t.Fatalf("Unexpected payload bytes found. Expected: %+v - Found: %+v.", []byte("hey"), payload)
		}
		w.Write(nil)
	}))
	defer ts.Close()

	s := NewStream(ts.URL)
	s.DisableHTTPS()
	s.SetMethod(http.MethodPut)
	if err := s.fireRequest([]byte("hey")); err != nil {
		t.Fatalf("Unexpected error: %s", err.Error())
	}
}

// TestFireRequestFailure covers the possible error generated by
// fireRequest function.
func TestFireRequestFailure(t *testing.T) {
	s := NewStream("invalid-url.com")
	if err := s.fireRequest([]byte("hey")); err == nil {
		t.Fatalf("This request should have failed, found nil error instead.")
	}

	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write(nil)
	}))
	defer ts.Close()

	s = NewStream(ts.URL)
	s.SetMethod("NOT A METHOD")
	if err := s.fireRequest([]byte("hey")); err == nil {
		t.Fatalf("This request should have failed, found nil error instead.")
	}
}

// TestWriteSuccess successfully uses Write stream entrypoint.
func TestWriteSuccess(t *testing.T) {
	timedout := true
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		if r.Method != http.MethodPut {
			w.Write(nil)
			t.Fatalf("Unexpected request method. Expected: %s - Found: %s.", http.MethodPut, r.Method)
		}

		// Read body.
		payload, err := ioutil.ReadAll(r.Body)
		if err != nil {
			w.Write(nil)
			t.Fatalf("Error reading body: %v", err)
			return
		}
		defer r.Body.Close()

		if len(payload) != 6 {
			w.Write(nil)
			t.Fatalf("Unexpected number of bytes read. Expected: %d - Found: %d.", 6, len(payload))
		}
		if bytes.Compare(payload, []byte("hey ho")) != 0 {
			w.Write(nil)
			t.Fatalf("Unexpected payload bytes found. Expected: %+v - Found: %+v.", []byte("hey ho"), payload)
		}
		timedout = false
		w.Write(nil)
	}))
	defer ts.Close()

	s := NewStream(ts.URL)
	s.DisableHTTPS()
	s.SetMethod(http.MethodPut)

	s.SetCustomBodyPrepareFunction(func(in []byte) ([]byte, error) {
		stringed := string(in)
		return []byte(stringed + " ho"), nil
	})

	nbytes, err := s.Write([]byte("hey"))
	if err != nil {
		t.Fatalf("Unexpected error: %s", err.Error())
	}
	if nbytes != 6 {
		t.Fatalf("Unexpected number of written bytes. Expected: %d - Found: %d.", 6, nbytes)
	}

	// Sleep a bit to let the handler process the request.
	time.Sleep(5 * time.Second)
	if timedout {
		t.Fatalf("No successful request was received by the test handler and it timed out.")
	}
}

// TestWritePrepareBodyFails verifies what happens when the provided
// body prepare function fails.
func TestWritePrepareBodyFails(t *testing.T) {
	s := NewStream("unneded.url")
	s.DisableHTTPS()
	s.SetMethod(http.MethodPut)

	s.SetCustomBodyPrepareFunction(func(in []byte) ([]byte, error) {
		return nil, fmt.Errorf("an-error")
	})

	nbytes, err := s.Write([]byte("hey"))
	if err == nil {
		t.Fatalf("An error was expected!")
	}
	if err.Error() != "custom body prepare failed due to: an-error" {
		t.Fatalf("Unexpected error value found. Expected: `%s` - Found: `%s`.", "custom body prepare failed due to: an-error", err.Error())
	}
	if nbytes != 0 {
		t.Fatalf("Unexpected number of written bytes. Expected: %d - Found: %d.", 0, nbytes)
	}
}
